In [3]:
import pandas as pd

# Load all query result CSVs
wq2  = pd.read_csv("WQ2.csv")
wq3  = pd.read_csv("WQ3.csv")
wq4  = pd.read_csv("WQ4.csv")

wq7  = pd.read_csv("WQ7.csv")
wq8  = pd.read_csv("WQ8.csv")
wq9  = pd.read_csv("WQ9.csv")
wq10 = pd.read_csv("WQ10.csv")
wq13 = pd.read_csv("WQ13.csv")
wq14 = pd.read_csv("WQ14.csv")
wq15 = pd.read_csv("WQ15.csv")
wq16 = pd.read_csv("WQ16.csv")
wq17 = pd.read_csv("WQ17.csv")
wq18 = pd.read_csv("WQ18.csv")
wq19 = pd.read_csv("WQ19.csv")
wq20 = pd.read_csv("WQ20.csv")
wq21 = pd.read_csv("WQ21.csv")
wq24 = pd.read_csv("WQ24.csv")
wq25 = pd.read_csv("WQ25.csv")

print("All files loaded successfully!")

All files loaded successfully!

## Section A — Schema Exploration & Constraints

In [4]:
# Q1 — All customers in the ShopEase database
print(f"Total customers: {len(wq2)}")
wq2

Total customers: 9

  first_name last_name       city
0      Aarav    Sharma     Mumbai
1      Priya     Patel  Ahmedabad
2      Rohan     Gupta      Delhi
3      Sneha     Reddy  Hyderabad
4     Vikram     Singh     Jaipur
5     Ananya      Iyer    Chennai
6      Karan     Mehta       Pune
7      Divya      Nair      Kochi
8      Gauri   Dadhich     jaipur

In [5]:
# Q2 — Customer names and their cities
wq3

      category
0     Clothing
1  Electronics
2         Home

In [6]:
# Q3 — Distinct product categories
print(f"Total unique categories: {len(wq4)}")
wq4

Total unique categories: 6

          Field           Type Null  Key  Default  Extra
0       item_id            int   NO  PRI      NaN    NaN
1      order_id            int   NO  MUL      NaN    NaN
2    product_id            int   NO  MUL      NaN    NaN
3      quantity            int   NO  NaN      NaN    NaN
4    unit_price  decimal(10,2)   NO  NaN      NaN    NaN
5  discount_pct   decimal(5,2)  YES  NaN      0.0    NaN

**Q4 — Primary Keys (DESC output)**
Primary keys identified: `customer_id`, `product_id`, `order_id`, `item_id`.
Primary keys must be UNIQUE and NOT NULL to uniquely identify every row.

**Q5 — UNIQUE Constraint on email**
Inserting a duplicate email raises: *Duplicate entry for UNIQUE key*.
Ensures one email per customer — data integrity maintained.

**Q6 — CHECK Constraint on unit_price**
Inserting `unit_price = -50` raises: *Check constraint violated*.
The constraint `unit_price > 0` blocks invalid negative prices.

## Section B — Filtering with WHERE, AND, BETWEEN

In [10]:
# Q7 — All delivered orders
print(f"Total delivered orders: {len(wq7)}")
wq7

Total delivered orders: 6

   order_id  customer_id  order_date     status  total_amount
0      1001          101  2024-08-01  Delivered        4498.0
1      1002          102  2024-08-03  Delivered         799.0
2      1004          101  2024-08-10  Delivered        3499.0
3      1006          105  2024-08-15  Delivered        5898.0
4      1008          103  2024-08-20  Delivered         899.0
5      1010          108  2024-08-28  Delivered        1598.0

In [32]:
# Q8 — Electronics products priced above ₹2000
print(f" {len(wq8)}")
wq8

 2

   product_id       product_name     category  brand  unit_price  stock_qty
0         203        Smart Watch  Electronics  Noise      2999.0        150
1         205  Bluetooth Speaker  Electronics    JBL      3499.0        200

In [13]:
# Q9 — Customers from Maharashtra who joined in 2024
print(f"Maharashtra customers (2024): {len(wq9)}")
wq9

Maharashtra customers (2024): 2

,customer_id,first_name,last_name,email,city,state,join_date,is_premium
0,101,Aarav,Sharma,aarav.s@email.com,Mumbai,Maharashtra,2024-01-15,1
1,107,Karan,Mehta,karan.m@email.com,Pune,Maharashtra,2024-07-22,1

In [33]:
# Q10 — Orders between Aug 10–25 excluding Cancelled
print(f"Active orders in date range: {len(wq10)}")
wq10

Active orders in date range: 5

   order_id  customer_id  order_date     status  total_amount
0      1004          101  2024-08-10  Delivered        3499.0
1      1006          105  2024-08-15  Delivered        5898.0
2      1007          106  2024-08-18    Pending        1299.0
3      1008          103  2024-08-20  Delivered         899.0
4      1009          107  2024-08-25    Shipped        6098.0

-- Q11)
/*
The idx_orders_date index is created on the order_date column of the orders table.
It helps MySQL find records for a particular date faster instead of checking every row
in the table,It assigns a seprate memory to the column where data is orgainized in ordered format hence takes (log n) time
and there is a pointer to the memory location of the row containing that column.
This improves query performance, especially when the table contains a
large number of orders.

Example:
SELECT * FROM orders
WHERE order_date = '2024-08-15';
*/

-- Q12)
/*
No, the index on join_date would not be used efficiently in the query
WHERE YEAR(join_date) = 2024 because MySQL first has to calculate the
YEAR value for every row and then compare it with 2024. Since a function
is applied on the indexed column, MySQL cannot directly use the index and
may end up scanning the whole table.

A better approach is to use a date range:
*/

SELECT * FROM customers
WHERE join_date >= '2024-01-01'
AND join_date < '2025-01-01';
/*

This query gives the same result but allows MySQL to use the index on
join_date directly. Instead of checking every row, it can quickly find
all records whose join_date falls within the given range, making the
query faster and more efficient.
*/

## Section C — Aggregate Functions & GROUP BY

In [15]:
# Q13 — Total number of orders
wq13

   total_order
0           11

In [17]:
# Q14 — Total revenue from Delivered orders only
wq14

   total_revenue
0        17191.0

In [18]:
# Q15 — Average price per product category
wq15

      category  AVG_PRICE
0     Clothing     2699.0
1  Electronics     2224.0
2         Home      949.0

In [19]:
# Q16 — Order count and revenue grouped by status
print("Revenue breakdown by order status:")
wq16

Revenue breakdown by order status:

      status  count_of_orders  total_revenue
0  Delivered                6        17191.0
1    Shipped                2        13596.0
2  Cancelled                1         2999.0
3    Pending                2         2897.0

In [20]:
# Q17 — Most and least expensive product per category
wq17

      category  most_expensive  less_expensive
0     Clothing          4599.0           799.0
1  Electronics          3499.0           899.0
2         Home          1299.0           599.0

In [24]:
# Q18 — Categories where average price exceeds ₹2000 (HAVING clause)
print(f"High-value categories: {len(wq18)}")
wq18

High-value categories: 2

      category  avg_price
0     Clothing     2699.0
1  Electronics     2224.0

## Section D — JOINs & Relationships

In [23]:
# Q19 — INNER JOIN: customers with their orders
print(f"Matched customer-order records: {len(wq19)}")
wq19

Matched customer-order records: 11

    customer_id first_name last_name  order_id  order_date  total_amount
0           101      Aarav    Sharma      1001  2024-08-01        4498.0
1           102      Priya     Patel      1002  2024-08-03         799.0
2           103      Rohan     Gupta      1003  2024-08-05        7498.0
3           101      Aarav    Sharma      1004  2024-08-10        3499.0
4           104      Sneha     Reddy      1005  2024-08-12        2999.0
5           105     Vikram     Singh      1006  2024-08-15        5898.0
6           106     Ananya      Iyer      1007  2024-08-18        1299.0
7           103      Rohan     Gupta      1008  2024-08-20         899.0
8           107      Karan     Mehta      1009  2024-08-25        6098.0
9           108      Divya      Nair      1010  2024-08-28        1598.0
10          102      Priya     Patel      1011  2026-05-31        1598.0

In [28]:
# Q20 — LEFT JOIN: all customers including those with no orders
print(f" {len(wq20)}")
wq20

 12

   first_name last_name  customer_id  order_id
0       Aarav    Sharma          101    1001.0
1       Aarav    Sharma          101    1004.0
2       Priya     Patel          102    1002.0
3       Priya     Patel          102    1011.0
4       Rohan     Gupta          103    1003.0
5       Rohan     Gupta          103    1008.0
6       Sneha     Reddy          104    1005.0
7      Vikram     Singh          105    1006.0
8      Ananya      Iyer          106    1007.0
9       Karan     Mehta          107    1009.0
10      Divya      Nair          108    1010.0
11      Gauri   Dadhich          209       NaN

In [27]:
# Q21 — 3-table JOIN: order details with product names
print(f"{len(wq21)}")
wq21

15

    order_id          product_name  quantity  unit_price  discount_pct
0       1001      Wireless Earbuds         2      1499.0           0.0
1       1006      Wireless Earbuds         1      1499.0          10.0
2       1002        Cotton T-Shirt         1       799.0           0.0
3       1003           Smart Watch         1      2999.0           0.0
4       1005           Smart Watch         1      2999.0           0.0
5       1003         Running Shoes         1      4599.0           5.0
6       1006         Running Shoes         1      4599.0           5.0
7       1004     Bluetooth Speaker         1      3499.0           0.0
8       1009     Bluetooth Speaker         1      3499.0           0.0
9       1007          Bedsheet Set         1      1299.0           0.0
10      1010          Bedsheet Set         1      1299.0           0.0
11      1001          Laptop Stand         1       899.0          10.0
12      1008          Laptop Stand         1       899.0           0.0
13      1009  Cushion Covers (Set)         2       599.0          15.0
14      1010  Cushion Covers (Set)         1       599.0           0.0

/* Q22)
LEFT JOIN: LEFT JOIN returns all records from the left table and matching
records from the right table.
EX) SELECT c.customer_id, c.first_name, o.order_id
FROM   customers c LEFT JOIN orders o ON c.customer_id = o.customer_id;

RIGHT JOIN:returns all records from the right table and matching
records from the left table.
EX)SELECT c.customer_id, c.first_name, o.order_id
FROM   customers c RIGHT JOIN orders o ON c.customer_id = o.customer_id;

FULL OUTER JOIN:A FULL OUTER JOIN returns all records from both tables, whether
a match exists or not. It is useful when we want to see every
customer and every order, including unmatched records from both sides.
EX)SELECT c.customer_id, c.first_name, o.order_id
FROM   customers c LEFT  JOIN orders o ON c.customer_id = o.customer_id
UNION
SELECT c.customer_id, c.first_name, o.order_id
FROM   customers c RIGHT JOIN orders o ON c.customer_id = o.customer_id;
/*

-- Q23) implemented case when statement to identify foreign keys
SELECT
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = 'gauri'
AND REFERENCED_TABLE_NAME IS NOT NULL;
-- /*
Foreign Keys create relationships between tables and ensure referential integrity.
If we try to insert an order with customer_id = 999 and no customer with customer_id = 999 exists in the customers table,
MySQL will reject the insertion and generate a Foreign Key
constraint error. This prevents orders from being linked to customers that do
not exist in the database.
*/
INSERT INTO orders VALUES (201, 999, '2024-06-20', 'Pending', 5000);
--  shows ERROR-"Cannot add or update a child row: a foreign key constraint fails (`gauri`.`orders`, CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`customer_id`))"

-- SECTION E

## Section E — CASE WHEN, ACID & Transactions

In [29]:
# Q24 — Product price tiers using CASE WHEN
print("Price tier classification:")
wq24

Price tier classification:

           product_name  unit_price price_tier
0      Wireless Earbuds      1499.0  Mid Range
1        Cotton T-Shirt       799.0     Budget
2           Smart Watch      2999.0  Mid Range
3         Running Shoes      4599.0    Premium
4     Bluetooth Speaker      3499.0    Premium
5          Bedsheet Set      1299.0  Mid Range
6          Laptop Stand       899.0     Budget
7  Cushion Covers (Set)       599.0     Budget

In [30]:
# Q25 — Delivered vs Not Delivered in a single row
print("Order delivery summary (single row output):")
wq25

Order delivery summary (single row output):

   Delivered_Orders  Not_Delivered_Orders
0                 6                     5

 Q25)
 My thinking was to use this
SELECT
    CASE
       WHEN status = 'Delivered' THEN 'Delivered'
      ELSE 'Not Delivered'
    END AS order_type,
     COUNT(*) AS total_orders
 FROM orders
GROUP BY order_type;
 But it returns 2 rows and questions askr to return single row

SELECT
    COUNT(CASE WHEN status = 'Delivered' THEN 1 END) AS Delivered_Orders,
    COUNT(CASE WHEN status != 'Delivered' THEN 1 END) AS Not_Delivered_Orders
FROM orders;

 Q26)

/*
A - Atomicity:
Atomicity means a transaction is treated as a single unit. Either all
operations succeed or none of them do.The transaction will be in single account.

C - Consistency:
Consistency ensures that data remains valid before and after a transaction.
Database rules and constraints like UNIQUE,CHECK  should never be violated.

I - Isolation:
Isolation ensures that multiple transactions running at the same time
do not interfere with each other.they runs parallely without interfering in each other.

D - Durability:
Durability ensures that once a transaction is committed, the changes
are permanently saved even if the system crashes.

Bank Transfer Example:

Suppose ₹1000 is transferred from Account A to Account B.

Atomicity:
If money is deducted from A but not added to B due to an error, the
entire transaction is rolled back.

Consistency:
The total amount of money in the system remains unchanged after the transfer and maintains the current balance.

Isolation:
Two transfers happening at the same time should not affect each other's results.

Durability:
Once the transfer is completed and committed, the updated balances remain
saved even if the database server suddenly shuts down.
*/