In [15]:
import pandas as pd

ALL QUERY OUTPUTS

In [16]:
# Q1) Orders where sales > average sales (Subquery)
q1 = pd.read_csv("Q1.csv")
print(f"Total orders above average sales: {len(q1)}")
q1.head(10)

Total orders above average sales: 1000

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,FUR-BO-10001798,261.96,2,0.00,41.91
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,FUR-CH-10000454,731.94,3,0.00,219.58
2,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,FUR-TA-10000577,957.58,5,0.45,-383.03
3,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,TEC-PH-10002275,907.15,6,0.20,90.72
4,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,FUR-TA-10001539,1706.18,9,0.20,85.31
5,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,TEC-PH-10002033,911.42,4,0.20,68.36
6,CA-2016-161389,2016-12-05,2016-12-10,Standard Class,IM-15070,OFF-BI-10003656,407.98,3,0.20,132.59
7,CA-2014-105893,2014-11-11,2014-11-18,Standard Class,PK-19075,OFF-ST-10004186,665.88,6,0.00,13.32
8,CA-2015-106320,2015-09-25,2015-09-30,Standard Class,EB-13870,FUR-TA-10000577,1044.63,3,0.00,240.26
9,US-2015-150630,2015-09-17,2015-09-21,Standard Class,TB-21520,FUR-BO-10004834,3083.43,7,0.50,-1665.05

In [17]:
# Q2)Highest sales order per customer (Subquery)
q2 = pd.read_csv("Q2.csv")
print(f"Total customers: {len(q2)}")
q2.head(10)

Total customers: 795

  customer_id        order_id    sales
0    CG-12520  CA-2016-152156   731.94
1    SO-20335  US-2015-108966   957.58
2    BH-11710  CA-2014-115812  1706.18
3    EB-13870  CA-2015-106320  1044.63
4    TB-21520  US-2015-150630  3083.43
5    GH-14485  CA-2016-117590  1097.54
6    SN-20710  CA-2015-117415   532.40
7    JM-15265  CA-2016-105816  1029.95
8    TB-21055  CA-2016-111682   319.41
9    BS-11590  CA-2014-106376  1113.02

In [18]:
# Q3)Total sales per customer (CTE)
q3 = pd.read_csv("Q3.csv")
print(f"Total customers: {len(q3)}")
q3.head(10)

Total customers: 793

  customer_id  total_sales
0    CG-12520      1148.78
1    DV-13045      1119.48
2    SO-20335      2602.58
3    BH-11710      6255.34
4    AA-10480      1782.87
5    IM-15070      4930.49
6    HP-14815      1990.31
7    PK-19075      8158.65
8    AG-10270      2565.26
9    ZD-21925      1493.94

In [19]:
# Q4)Customers with above average total sales (CTE + Subquery)
q4 = pd.read_csv("Q4.csv")
print(f"Customers above average: {len(q4)}")
q4.head(10)

Customers above average: 299

  customer_id  total_sales
0    BH-11710      6255.34
1    IM-15070      4930.49
2    PK-19075      8158.65
3    TB-21520      4730.62
4    MA-17560      4280.62
5    SN-20710      3127.97
6    LC-16930      4481.16
7    RA-19885      3832.32
8    ES-14080      4648.52
9    KM-16720      4909.47

In [20]:
# Q5) Rank customers by total sales (Window Function)
q5 = pd.read_csv("Q5.csv")
q5.head(10)

  customer_id  total_sales  sales_rank
0    SM-20320     25043.07           1
1    TC-20980     19017.85           2
2    RB-19360     15117.35           3
3    TA-21385     14595.62           4
4    AB-10105     14355.61           5
5    SC-20095     14142.34           6
6    KL-16645     14071.92           7
7    HL-15040     12873.30           8
8    SE-20110     12209.44           9
9    CC-12370     12129.08          10

In [21]:
# Q6)Row numbers per order within each customer (PARTITION BY)
q6 = pd.read_csv("Q6.csv")
q6.head(10)

,order_id,order_date,ship_date,ship_mode,customer_id,product_id,sales,quantity,discount,profit,row_num
0,CA-2016-103982,2016-03-03,2016-03-08,Standard Class,AA-10315,OFF-SU-10000151,3930.07,3,0.2,-786.01,1
1,CA-2014-128055,2014-03-31,2014-04-05,Standard Class,AA-10315,OFF-BI-10004390,673.57,2,0.2,252.59,2
2,CA-2016-103982,2016-03-03,2016-03-08,Standard Class,AA-10315,TEC-PH-10000895,431.98,3,0.2,32.40,3
3,CA-2017-147039,2017-06-29,2017-07-04,Standard Class,AA-10315,OFF-AP-10000576,362.94,3,0.0,90.74,4
4,CA-2014-128055,2014-03-31,2014-04-05,Standard Class,AA-10315,OFF-AP-10002765,52.98,2,0.0,14.83,5
5,CA-2016-103982,2016-03-03,2016-03-08,Standard Class,AA-10315,TEC-AC-10002857,41.72,7,0.2,5.74,6
6,CA-2015-121391,2015-10-04,2015-10-07,First Class,AA-10315,OFF-ST-10001590,26.96,2,0.0,7.01,7
7,CA-2014-138100,2014-09-15,2014-09-20,Standard Class,AA-10315,OFF-PA-10000349,14.94,3,0.0,7.02,8
8,CA-2014-138100,2014-09-15,2014-09-20,Standard Class,AA-10315,FUR-FU-10002456,14.56,2,0.0,6.26,9
9,CA-2017-147039,2017-06-29,2017-07-04,Standard Class,AA-10315,OFF-BI-10004654,11.54,2,0.0,5.77,10

In [22]:
# Q7)Top 3 customers by total sales (Window Function)
q7 = pd.read_csv("Q7.csv")
q7

  customer_id  total_sales  sales_rank
0    SM-20320     25043.07           1
1    TC-20980     19017.85           2
2    RB-19360     15117.35           3

In [23]:
# Final Combined Query — Name + Total Sales + Rank
combined = pd.read_csv("Combined quet.csv")
combined.head(20)

         customer_name  total_sales  sales_rank
0          Sean Miller     25043.07           1
1         Tamara Chand     19017.85           6
2         Raymond Buch     15117.35          11
3         Tom Ashbrook     14595.62          17
4        Adrian Barton     14355.61          21
5         Sanjit Chand     14142.34          29
6         Ken Lonsdale     14071.92          38
7         Hunter Lopez     12873.30          47
8         Sanjit Engle     12209.44          53
9   Christopher Conant     12129.08          64
10        Todd Sumrall     11885.87          69
11           Greg Tran     11820.12          74
12        Becky Martin     11609.91          84
13         Seth Vernon     11420.64          88
14     Caroline Jumper     11079.74          98
15         Clay Ludtke     10880.56         106
16       Maria Etezadi     10635.92         118
17      Karen Ferguson     10604.26         127
18        Bill Shonely     10501.65         134
19        Edward Hooks     10005.97         139

In [24]:
# Mini Project 1 Top 5 customers
mp1 = pd.read_csv("MP1.csv")
print("TOP 5 CUSTOMERS")
mp1

TOP 5 CUSTOMERS

  customer_id  total_sales  sales_rank
0    SM-20320     25043.07           1
1    TC-20980     19017.85           2
2    RB-19360     15117.35           3
3    TA-21385     14595.62           4
4    AB-10105     14355.61           5

In [25]:
# Mini Project 2  Bottom 5 customers
mp2 = pd.read_csv("MP2.csv")
print("BOTTOM 5 CUSTOMERS")
mp2

BOTTOM 5 CUSTOMERS

  customer_id  total_sales  sales_rank
0    TS-21085         4.84           1
1    LD-16855         5.30           2
2    MG-18205        12.32           3
3    CJ-11875        16.52           4
4    RS-19870        22.33           5

In [26]:
# Mini Project 3  Customers with only one order
mp3 = pd.read_csv("MP3.csv")
print(f"Customers with single order: {len(mp3)}")
mp3

Customers with single order: 6

  customer_id
0    JR-15700
1    MG-18205
2    AO-10810
3    LD-16855
4    CJ-11875
5    RE-19405

In [27]:
# Mini Project 4  Customers with above-average sales
mp4 = pd.read_csv("MP4.csv")
print(f"Above average customers: {len(mp4)}")
mp4.head(10)

Above average customers: 299

  customer_id  total_sales
0    BH-11710      6255.34
1    IM-15070      4930.49
2    PK-19075      8158.65
3    TB-21520      4730.62
4    MA-17560      4280.62
5    SN-20710      3127.97
6    LC-16930      4481.16
7    RA-19885      3832.32
8    ES-14080      4648.52
9    KM-16720      4909.47

In [28]:
# Mini Project 5  Highest order value per customer
mp5 = pd.read_csv("MP5.csv")
mp5.head(10)

  customer_id  highest_order_value
0    CG-12520               731.94
1    DV-13045               721.88
2    SO-20335               957.58
3    BH-11710              1706.18
4    AA-10480               479.97
5    IM-15070              1819.86
6    HP-14815              1242.90
7    PK-19075              4305.55
8    AG-10270              1336.44
9    ZD-21925               823.96

#BRIEF INSIGHTS

## Brief Insights

Solving this assignment , I learned how to use MySQL Workbench for working with datasets and performing SQL analysis. I imported the Superstore dataset, created separate tables, and used SQL queries to analyze customer sales data that was something new i explored. Then perfomed the queries given in assignment.

Customers Table : 4835 records
Products Table  : 1842 records
Orders Table    : 9693 records

* Identified the top and bottom customers based on total sales.
* Found customers who placed only one order.
* Compared customer sales with the average sales to identify high-value customers.
* Calculated the highest order value for each customer.
* Ranked customers based on their total sales using window functions.
* Used CTEs, subqueries, joins, and window functions to answer business-related questions.

This project helped me improve my SQL skills especially the typicall topics like CTE and gain hands-on experience using real-world sales data.